name: Run Tests API and Worker

on:
  pull_request:
  workflow_dispatch:

env:
  TOKEN: test

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘€ Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: ğŸ”¨ Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: ğŸ¯ Cache hit!
        if: steps.setup-rye.outputs.cache-hit == 'true'
        run: echo "Rye cache was restored"

      - name: ğŸ”„ Sync dependencies
        run: |
          UV_INDEX_STRATEGY=unsafe-first-match rye sync --no-lock

      - name: ğŸ˜­ Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libgeos-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            binutils \
            curl \
            git \
            autoconf \
            automake \
            build-essential \
            libtool \
            gcc \
            libmagic-dev \
            poppler-utils \
            tesseract-ocr \
            libreoffice \
            libpq-dev \
            pandoc

      - name: ğŸ”½ Download and Install NATS Server
        run: |
          curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@v2.10.20 | sh

      - name: ğŸ› ï¸ Set up NATS config
        run: |
          cat << EOF > config.conf
          # General config
          listen: 0.0.0.0:4222
          # Auth
          authorization: {
              token: $TOKEN
          }
          tls: {
            cert_file: "./libs/megaparse_sdk/tests/cert/client-cert.pem"
            key_file: "./libs/megaparse_sdk/tests/cert/client-key.pem"
            verify: true
          }
          # Avg knowledge_size: 1.5MB
          # Std knowledge_size: 4.72MB
          # p99.9 mean +4-std-dev: 1.5MB+3*4MB ~ 20MB
          # Limits: 3 env * 3 workers * 10msg/clients pending * max_payload ~ 2GB of ram
          max_payload: 20MB
          max_pending: 200MB

          # Monitoring
          https_port: 8222
          EOF

      - name: ğŸ”Œ Start NATS Server
        run: |
          nohup nats-server -c config.conf > nats.log 2>&1 &

      - name: ğŸš€ Run tests
        run: |
          rye test -p megaparse-sdk
